<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexon.Core\Lexon.Core.csproj" />
    <ProjectReference Include="..\Lexon.Storage\Lexon.Storage.csproj" />
    <ProjectReference Include="..\Lexon.Profiles\Lexon.Profiles.csproj" />
    <ProjectReference Include="..\Lexon.Ui\Lexon.Ui.csproj" />
  </ItemGroup>

</Project>
